### ISSUE TITLE
Transaction در زیرساخت DNTFrameworkCore

### ISSUE THREAD

**Issue by Azaferany** [rabbal/DNTFrameworkCore#11]
استفاده می کنم ایجاد میشهTransactionalAttributeارور زیر وقتی از 

```
System.InvalidOperationException: The configured execution strategy 'SqlServerRetryingExecutionStrategy' does not support user initiated transactions. Use the execution strategy returned by 'DbContext.Database.CreateExecutionStrategy()' to execute all the operations in the transaction as a retriable unit.
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.OnFirstExecution()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

**Comment by rabbal** [comment]
<div dir="rtl">
اگر مکانیزم سعی مجدد را در تنظیمات DbContext برنامه خود توسط متد EnableRetryOnFailure فعال کرده باشید با این مشکل برخورد خواهید کرد. از آنجایی که در پشت زمینه، توسط زیرساخت به صورت صریح تراکنش ها توسط متد BeginTransaction ایجاد خواهند شد، لذا این محدودیت در استفاده از مکانیزم سعی مجدد را خواهید داشت؛ متن خطا نیز به همین موضوع اشاره می کند.

**Comment by Azaferany** [comment]
با تشکر از پاسخ تون
